### ISSUE TITLE
Native Linux Build Failure (Ansible)

### ISSUE THREAD

**Issue by aremorov** [waiwera/waiwera#15] opened 2023-02-24 01:18 UTC
I am getting the following error when I follow the native linux install guide with ansible:

aremorov@DESKTOP-C0SSMEB:~/W1/install$ ansible-playbook ansible/install_local.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed in
 version 2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ERROR! couldn't resolve module/action 'make'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/aremorov/W1/install/ansible/roles/petsc/tasks/main.yml': line 44, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      block:
      - name: make all
        ^ here

It seems like the error is the indentation of main.yml, but when I looked through that file, everything seemed correct. Any advice on how to resolve this?
Thanks

**Comment by acroucher** [comment] 2023-02-24 01:25
I don't think there's a problem with the yaml files, as they are working fine elsewhere. I think it's more likely due to something about the way your system is configured.

What OS and version are you using? And what version of Ansible?

**Comment by aremorov** [comment] 2023-02-24 01:38
I am using Ubuntu 20.04.5 LTS on WSL, the ansible version is core 2.13.7.

**Comment by acroucher** [comment] 2023-02-24 01:48
Ah, I think WSL is your problem then. I helped another user try a native Linux install on WSL but it never worked - WSL just isn't "native" Linux. If you need to run on Windows I think using Docker is your best bet.

**Comment by aremorov** [comment] 2023-02-24 02:12
I normally use Docker which works great, but now trying to get waiwera working on HPC servers, so I'm trying to figure out the native installation. They don't support Docker but use Singularity, and when I converted the waiwera Docker image to Singularity, the "waiwera" command didn't work so it seems like some functionality was lost.
I just tried the native Linux install on a real Linux machine (dual boot), Ubuntu 20.04.5 LTS, but I still get the same error:

(base) aremorov@aremorov-Alienware-Aurora-R9:~/Desktop/W1/install$ ansible-playbook ansible/install_local.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks 
instead. See https://docs.ansible.com/ansible-
core/2.14/user_guide/playbooks_reuse_includes.html for details. This feature 
will be removed in version 2.16. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
ERROR! couldn't resolve module/action 'make'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/aremorov/Desktop/W1/install/ansible/roles/petsc/tasks/main.yml': line 44, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      block:
      - name: make all
        ^ here

**Comment by acroucher** [comment] 2023-02-24 02:45
Hmm, that is odd then... the Waiwera CI runs on Github Actions all the time, using Ubuntu VMs - these are Ubuntu 22.04 now but were 20.04 until about last year. We also use Ansible to install Waiwera in the cloud (AWS and Azure) with no problems.

What version of Ansible are you running on the Alienware machine? I'm just wondering if there's been some recent breaking update to Ansible. If possible/easy you could try downgrading Ansible to an earlier version to see if that works.

I have installed Waiwera on our local HPC cluster (Cray XC50) but for that I did not use Ansible - mainly because I wanted/needed to have a bit more control over things and build PETSc separately myself. The Ansible install *usually* works well for typical installs where the user just wants it to be as easy as possible. For HPC sometimes things are configured a bit differently and more control is needed. So I used the Waiwera `config.py` script instead (I wrote that before we started using Ansible). I can help you try that if you like.

**Comment by aremorov** [comment] 2023-02-24 03:25
I am using ansible 2.14.1. I tried downgrading, but only 2.13 worked (there were errors running ansible when I tried versions 2.11, 2.12: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#node-requirement-summary), but I still got the same error when running ansible-playbook ansible/install_local.yml 

I would be very grateful if you could help me with the config.py script.

**Comment by acroucher** [comment] 2023-02-24 04:10
`config.py`  is mostly just a wrapper for running `meson build` with appropriate arguments. It also downloads and builds the PETSc library if it doesn't detect one already installed (if it does, it will use that). It assumes you already have the required tools (git, compilers, ninja, meson etc.) installed (all that stuff that Ansible does for you).

Typical use case is that you have a home directory, e.g. `/home/bob/`, you want to install to. So Waiwera will be installed to `/home/bob/bin`, and various libraries will be installed to `/home/bob/lib`.

It uses `pkg-config` to find libraries, so you need to set the pkg-config path (can add this to your `/home/bob/.bash_profile` to make it persistent):

```bash
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/home/bob/lib/pkgconfig"
```

Then clone Waiwera and run the config, e.g. supposing you want to build Waiwera in `/home/bob/waiwera/`:

```bash
mkdir -p /home/bob/waiwera
cd /home/bob/waiwera
git clone git@github.com:waiwera/waiwera.git .
python config.py
ninja -C build
python unit_tests.py
ninja -C build install
```

There are a bunch of optional arguments to `config.py`  if you want to configure things differently from the defaults, e.g. build dir name, debug/release version, installing somewhere other than the home dir, specifying the PETSc version etc. You can check in the `config.py` script to see what they are.

For HPC there are often other issues, e.g. you may have to use a provided MPI wrapper compiler instead of linking to MPI libraries - on the Cray XC50 you have to use the `ftn` wrapper compiler, which you can do using e.g.:

```bash
FC=ftn python config.py --mpi_wrapper_compiler=True
```

You will probably also need to load the appropriate modules before any of this, e.g. to get the right compilers. We have generally used the GNU compilers for Waiwera - in principle others should work too but they have not had much testing.

**Comment by aremorov** [comment] 2023-03-01 00:14
Thanks for the thorough description! I tried python config.py on the server, but got the error:


Run-time dependency MPI for fortran found: YES 4.0.3
Found CMake: /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/cmake (3.16.5)
DEPRECATION: CMake support for versions <3.17 is deprecated since Meson 0.62.0.
|
|   However, Meson was only able to find CMake 3.16.5.
|
|   Support for all CMake versions below 3.17.0 will be removed once
|   newer CMake versions are more widely adopted. If you encounter
|   any errors please try upgrading CMake to a newer version first.

Run-time dependency petsc found: NO (tried pkgconfig and cmake)

../meson.build:12:0: ERROR: Dependency "PETSc" not found, tried pkgconfig and cmake

A full log can be found at /home/aremorov/waiwera/waiwera-master/build/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
(ENV) [aremorov@narval4 waiwera-master]$


The full log (meson-log.txt) is attached. Any recommendations? 
[meson-log.txt](https://github.com/waiwera/waiwera/files/10855816/meson-log.txt)



Also, when I try just running a docker container from the waiwera/waiwera image (instead of waiwera-dkr), I get the error:

2023-02-28 18:50:05 ls: cannot access '/data/.idcheck': No such file or directory
2023-02-28 18:50:05 ls: cannot access '/data/.idcheck': No such file or directory
2023-02-28 18:50:05 + exec gosu waiwera
2023-02-28 18:50:05 Usage: gosu user-spec command [args]
2023-02-28 18:50:05    ie: gosu tianon bash
2023-02-28 18:50:05        gosu nobody:root bash -c 'whoami && id'
2023-02-28 18:50:05        gosu 1000:1 id
2023-02-28 18:50:05 
2023-02-28 18:50:05 gosu version: 1.10 (go1.7.1 on linux/amd64; gc)
2023-02-28 18:50:05      license: GPL-3 (full text at https://github.com/tianon/gosu)

I've had this error on several different machines. Is there some command that I can run alongside "docker run" that can fix this?

Thanks

**Comment by acroucher** [comment] 2023-03-01 01:18
> Thanks for the thorough description! I tried python config.py on the server, but got the error:

> Run-time dependency MPI for fortran found: YES 4.0.3
> Found CMake: /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/cmake (3.16.5)
> DEPRECATION: CMake support for versions <3.17 is deprecated since Meson 0.62.0.

This looks like a problem with the version of Meson you're using. Because Meson is still under fairly heavy development and the Fortran support is sometimes patchy, I usually stick to an earlier version which I know works, e.g. between 0.48 and 0.52. (This is again the kind of stuff that Ansible takes care of but if you're doing a more manual build using config.py you need to sort those kinds of issues out yourself.)

> Also, when I try just running a docker container from the waiwera/waiwera image (instead of waiwera-dkr), I get the error:

I would not recommend trying to run the Docker image without going through waiwera-dkr. It handles quite a lot of stuff particularly to do with sharing filesystems between your machine and the Docker image, which are otherwise quite tricky.

**Comment by aremorov** [comment] 2023-03-01 02:15
I tried it with meson version 0.51, but I still get the PETSc error:


Building PETSc:
/home/aremorov/waiwera/waiwera-master/external/PETSc/lib/petsc/conf/rules:817: /home/aremorov/waiwera/waiwera-master/external/PETSc/release/lib/petsc/conf/petscrules: No such file or directory
make[1]: *** No rule to make target '/home/aremorov/waiwera/waiwera-master/external/PETSc/release/lib/petsc/conf/petscrules'.  Stop.
gmakefile:67: release/lib/petsc/conf/files: No such file or directory
make: *** [GNUmakefile:17: /home/aremorov/waiwera/waiwera-master/external/PETSc/release/include/petscconf.h] Error 2
/home/aremorov/waiwera/waiwera-master/external/PETSc/lib/petsc/conf/rules:817: /home/aremorov/waiwera/waiwera-master/external/PETSc/release/lib/petsc/conf/petscrules: No such file or directory
make[1]: *** No rule to make target '/home/aremorov/waiwera/waiwera-master/external/PETSc/release/lib/petsc/conf/petscrules'.  Stop.
/home/aremorov/waiwera/waiwera-master/external/PETSc/lib/petsc/conf/variables:101: /home/aremorov/waiwera/waiwera-master/external/PETSc/release/lib/petsc/conf/petscvariables: No such file or directory
make: *** [GNUmakefile:17: /home/aremorov/waiwera/waiwera-master/external/PETSc/release/lib/petsc/conf/petscvariables] Error 2
The Meson build system
Version: 0.51.0
Source dir: /home/aremorov/waiwera/waiwera-master
Build dir: /home/aremorov/waiwera/waiwera-master/build
Build type: native build
Project name: waiwera
Project version: 1.3.1
Fortran compiler for the build machine: gfortran (gcc 9.3.0 "GNU Fortran (GCC) 9.3.0")
C compiler for the build machine: ccache cc (gcc 9.3.0 "cc (GCC) 9.3.0")
Fortran compiler for the host machine: gfortran (gcc 9.3.0 "GNU Fortran (GCC) 9.3.0")
C compiler for the host machine: ccache cc (gcc 9.3.0 "cc (GCC) 9.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Run-time dependency MPI for fortran found: YES 4.0.3
Found CMake: /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/cmake (3.16.5)
Run-time dependency petsc found: NO (tried pkgconfig and cmake)

meson.build:12:0: ERROR: Dependency "PETSc" not found, tried pkgconfig and cmake

A full log can be found at /home/aremorov/waiwera/waiwera-master/build/meson-logs/meson-log.txt


even though I installed and configured PETSc according to https://petsc.org/release/install/install_tutorial/.

**Comment by acroucher** [comment] 2023-03-01 02:27
I wouldn't recommend building your own PETSc separately unless you know what you're doing - better to let `config.py` do it. You would need to build the right version of PETSc to work with Waiwera and it has to be configured with a bunch of particular options and external dependencies itself (you can see what they are in the `petsc_config()` function inside `config.py`.)  You would also need to copy PETSc's pkg-config file to the right place so that pkg-config can find PETSc when it's building Waiwera. None of this sort of thing is covered in the simple "quick start" PETSc building tutorial  you were looking at.

If I were you I'd wipe out the PETSc you built and start the Waiwera config again (delete old build dir first), and let `config.py` build PETSc for you.

**Comment by aremorov** [comment] 2023-03-01 02:39
Building PETSc:
/home/aremorov/waiwera/external/PETSc/lib/petsc/conf/rules:817: /home/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/petscrules: No such file or directory
make[1]: *** No rule to make target '/home/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/petscrules'.  Stop.
gmakefile:67: release/lib/petsc/conf/files: No such file or directory
make: *** [GNUmakefile:17: /home/aremorov/waiwera/external/PETSc/release/include/petscconf.h] Error 2
/home/aremorov/waiwera/external/PETSc/lib/petsc/conf/rules:817: /home/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/petscrules: No such file or directory
make[1]: *** No rule to make target '/home/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/petscrules'.  Stop.
/home/aremorov/waiwera/external/PETSc/lib/petsc/conf/variables:101: /home/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/petscvariables: No such file or directory
make: *** [GNUmakefile:17: /home/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/petscvariables] Error 2
The Meson build system
Version: 0.51.0
Source dir: /home/aremorov/waiwera
Build dir: /home/aremorov/waiwera/build
Build type: native build
Project name: waiwera
Project version: 1.3.1
Fortran compiler for the build machine: gfortran (gcc 9.3.0 "GNU Fortran (GCC) 9.3.0")
C compiler for the build machine: ccache cc (gcc 9.3.0 "cc (GCC) 9.3.0")
Fortran compiler for the host machine: gfortran (gcc 9.3.0 "GNU Fortran (GCC) 9.3.0")
C compiler for the host machine: ccache cc (gcc 9.3.0 "cc (GCC) 9.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Run-time dependency MPI for fortran found: YES 4.0.3
Found CMake: /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/cmake (3.16.5)
Run-time dependency petsc found: NO (tried pkgconfig and cmake)

meson.build:12:0: ERROR: Dependency "PETSc" not found, tried pkgconfig and cmake

A full log can be found at /home/aremorov/waiwera/build/meson-logs/meson-log.txt


I removed the old waiwera build directory and PETSc build directory, and redid config.py, but still get this. Did I have to do something additional to just deleting the directory where I originally installed PETSc, in order to fully wipe PETSc from the system?

**Comment by acroucher** [comment] 2023-03-01 02:42
At long as pkg-config can't find any other PETScs it shouldn't matter. What is the output from:

```bash
pkg-config --libs PETSc
```

**Comment by aremorov** [comment] 2023-03-01 02:44
(ENV) [aremorov@narval4 waiwera]$ pkg-config --libs PETSc
Package PETSc was not found in the pkg-config search path.
Perhaps you should add the directory containing `PETSc.pc'
to the PKG_CONFIG_PATH environment variable
No package 'PETSc' found

**Comment by acroucher** [comment] 2023-03-01 02:51
That is healthy then. What was the output of `config.py` before it got to "Building PETSc:"?

It should have said something like "PETSc library not found: installing PETSc in /home/aremorov/waiwera/external/PETSc/"?

**Comment by aremorov** [comment] 2023-03-01 02:53
yep, that is the first thing it said, and then I think it started cloning it:

(ENV) [aremorov@narval4 waiwera]$ python config.py
PETSc library not found: installing PETSc in /home/aremorov/waiwera/external/PETSc
Cloning into '.'...
remote: Enumerating objects: 1068327, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1068327 (delta 0), reused 0 (delta 0), pack-reused 1068323
Receiving objects: 100% (1068327/1068327), 329.97 MiB | 29.91 MiB/s, done.
Resolving deltas: 100% (820099/820099), done.
Updating files: 100% (10775/10775), done.
Updating files: 100% (8005/8005), done.
Note: switching to 'v3.15.5'.

**Comment by acroucher** [comment] 2023-03-01 03:21
Hmm, this is odd...

It is complaining about not being able to find the file `/home/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/petscrules`.

Does the directory exist: `/home/aremorov/waiwera/external/PETSc/release`?

And what is the output from

```bash
grep "PETSC_ARCH=" /home/aremorov/waiwera/external/PETSc/configure.log
```

**Comment by aremorov** [comment] 2023-03-01 03:23
Yes, /home/aremorov/waiwera/external/PETSc/release exists and contains: bin, include and lib.

The output from the grep command is: 
PETSC_ARCH=release

**Comment by acroucher** [comment] 2023-03-01 03:27
OK, that's all as it should be... but presumably the file `/home/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/petscrules` doesn't exist?

**Comment by aremorov** [comment] 2023-03-01 03:30
Nope, only configure.log is in /home/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/.

**Comment by acroucher** [comment] 2023-03-01 03:35
Can you post the contents of that `configure.log`, if it's not too big?

If it is too big, might be better to email it to me (my email address can be found  [here](https://profiles.auckland.ac.nz/a-croucher)).

**Comment by aremorov** [comment] 2023-03-01 03:40
Sent over email

**Comment by acroucher** [comment] 2023-03-01 03:59
Thanks, it looks like the problem is because you have got both Intel and GCC compilers installed on your machine... in the Waiwera build Meson is detecting and using GCC but in the PETSc build, it looks like Intel has taken over the `mpicc` command. So PETSc is being built with that. When it comes to assigning compiler options it is trying to assign GCC compiler options to the Intel compiler, and that is failing. Even if it didn't, I doubt it would work to have PETSc being built with one compiler and Waiwera with another.

Is there some way for you to get your machine to associate the MPI wrapper compilers like `mpicc` with the GCC compilers instead of Intel? It might involve changing the `OMPI_CC` environment variable (maybe `OMPI_CXX` as well) - e.g. `OMPI_CC=gcc` - though I have never had to do that, so I don't know for sure.

**Comment by acroucher** [comment] 2023-03-01 04:06
Or if this is your compute cluster you're building on, there might be a module you can swap to get mpicc to use GCC. That's how it works on the cluster I use, but it may be totally different on your system.

**Comment by aremorov** [comment] 2023-03-01 04:25
I changed the mpicc to work with gcc instead of intel by loading gcc/9.3.0 (and it gave a message saying that gcc was going to be used instead of intel), and running mpicc -showme gave: 
gcc -I/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/openmpi/4.0.3/include -L/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/openmpi/4.0.3/lib -lmpi

However I still got the PETSc error. I am sending you the configure.log file.

**Comment by acroucher** [comment] 2023-03-01 04:50
OK, this is actually not the same error. The mpicc issue has been fixed and PETSc is now being built with gcc. But now it is complaining that it doesn't recognise the compiler optimisation option '-O3':

```
              Rejecting compiler flag '-O3 -march=native -mtune=native'  due to 
cc1: error: argument to ‘-O’ should be a non-negative integer, ‘g’, ‘s’ or ‘fast’
```

This is a bit bizarre... last time I checked, 3 was a non-negative integer. I have never before seen '-O3' not being recognised. What happens if you write a minimal C program (e.g. "hello world") and try to build it with mpicc (or even just gcc), using -O3 optimisation?

**Comment by aremorov** [comment] 2023-03-01 05:00
How would I add in the -O3 flag?
Would it be:  gcc -o -O3 hello_world hello_world.c ?

**Comment by aremorov** [comment] 2023-03-01 05:01
When I do:
gcc -o hello_world hello_world.c -O3

it works, and ./hello_world outputs hello world

**Comment by aremorov** [comment] 2023-03-01 19:29
Is waiwera run on CPU or GPU processes? If it is CPU then I will try installing it on a CPU-focused server.

**Comment by acroucher** [comment] 2023-03-01 22:44
Yes, CPU, so you should be installing on a CPU-focused server.

At this point I don't know what is going on with the -O3 optimisation not being recognised in the PETSc build. You could try some other versions of GCC but that shouldn't make any real difference... I'm building with GCC 8.4 on the cluster here but also with 9.4.0 on my dev laptop and that is fine, plus the Ubuntu 22.04 VMs used in the Waiwera CI are using GCC 9.5.

**Comment by aremorov** [comment] 2023-03-02 18:34
I tried downloading waiwera on a CPU-focused server and got the same -O3 optimisation error. I asked support, and they said:

The problem is a string quoting issue. The compiler is being passed the
single argument '-O3 -march=native -mtune=native', which it interprets
as the -O flag with argument '3 -march=native -mtune=native'.

You need to find where the quotation marks are being inserted.

I sent you the new configure.log file over email.

**Comment by acroucher** [comment] 2023-03-02 22:31
I see. Odd that it's a problem on this machine but not other ones.

You could try unquoting those strings inside `config.py`, so change line 63 from:

```python
        flags = ["--with-debugging=0",
                 "COPTFLAGS='-O3 -march=native -mtune=native'",
                 "CXXOPTFLAGS='-O3 -march=native -mtune=native'",
                 "FOPTFLAGS='-O3 -march=native -mtune=native'"]
```

to:

```python
        flags = ["--with-debugging=0",
                 "COPTFLAGS=-O3 -march=native -mtune=native",
                 "CXXOPTFLAGS=-O3 -march=native -mtune=native",
                 "FOPTFLAGS=-O3 -march=native -mtune=native"]
```
I would have thought those quotes are needed, so I'm not sure if this will work, but give it a try.

**Comment by aremorov** [comment] 2023-03-03 03:03
I think this helped significantly, its not giving me an error, but its at the stage of configuring PETSc:

Compiling Triangle; this may take several minutes 

and it has been at this stage for a very long time (2 hours). Is there a way around this?

**Comment by acroucher** [comment] 2023-03-03 03:05
it shouldn't take that long - usually about half an hour for the whole build. I would probably stop it and have a look at the configure.log file to see what is going on.

**Comment by aremorov** [comment] 2023-03-03 03:19
There is no configure.log file since I manually stop the process.

**Comment by aremorov** [comment] 2023-03-03 03:22
These are the lines output in the terminal during the PETSc configuration:

================================================================================                                                                                                                              =============
                      Configuring PETSc to compile on your system                                                                                                                                             
================================================================================                                                                                                                              =============
================================================================================                                                                                                                                    ***** WARNING: CC (set to mpicc) found in environment variables - ignoring                                                                                                                                     use ./configure CC=$CC if you really want to use that value ******                                                                                                                                     ================================================================================                                                                                                                              ================================================================================                                                                                                                                    ***** WARNING: CXX (set to mpicxx) found in environment variables - ignori                                                                                                                                     use ./configure CXX=$CXX if you really want to use that value ******                                                                                                                                   ================================================================================                                                                                                                              ================================================================================                                                                                                                                    ***** WARNING: FC (set to mpifort) found in environment variables - ignori                                                                                                                                     use ./configure FC=$FC if you really want to use that value ******                                                                                                                                     ================================================================================                                                                                                                              ================================================================================                                                                                                                                    ***** WARNING: F77 (set to mpif77) found in environment variables - ignori                                                                                                                                     use ./configure F77=$F77 if you really want to use that value ******                                                                                                                                   ================================================================================                                                                                                                              ================================================================================                                                                                                                                    ***** WARNING: F90 (set to mpif90) found in environment variables - ignori                                                                                                                                     use ./configure F90=$F90 if you really want to use that value ******                                                                                                                                   ================================================================================                                                                                                                              ================================================================================                                                                                                                                    ***** WARNING: You have a version of GNU make older than 4.0. It will work                                                                                                                                    but may not support all the parallel testing options. You can install the                                                                                                                                     latest GNU make with your package manager, such as brew or macports, or us                                                                                                                                    the --download-make option to get the latest GNU make *****                                                                                                                                             ================================================================================                                                                                                                              ================================================================================                                                                                                                                    It appears you do not have valgrind installed on your system.                                                                                                                                                 We HIGHLY recommend you install it from www.valgrind.org                                                                                                                                                      Or install valgrind-devel or equivalent using your package manager.                                                                                                                                           Then rerun ./configure                                                                                                                                                                                  ================================================================================                                                                                                                              ================================================================================                                                                                                                                    ***** WARNING: mpiexec may not work on your system due to network issues.                                                                                                                                     Perhaps you have VPN running whose network settings may not work with mpie                                                                                                                              ================================================================================                                                                                                                              ================================================================================                                                                                                                                    Trying to download git://https://bitbucket.org/petsc/pkg-sowing.git for SO                                                                                                                              ================================================================================                                                                                                                              ================================================================================                                                                                                                                    Running configure on SOWING; this may take several minutes                                                                                                                                              ================================================================================                                                                                                                              ================================================================================                                                                                                                                    Running make on SOWING; this may take several minutes                                                                                                                                                   ================================================================================                                                                                                                              ================================================================================                                                                                                                                    Running make install on SOWING; this may take several minutes                                                                                                                                           ================================================================================                                                                                                                              ================================================================================                                                                                                                                    Trying to download http://www.zlib.net/zlib-1.2.11.tar.gz for ZLIB                                                                                                                                      ================================================================================                                                                                                                              ================================================================================                                                                                                                                    Trying to download http://ftp.mcs.anl.gov/pub/petsc/externalpackages/zlib-                                                                                                                              ================================================================================                                                                                                                              ================================================================================                                                                                                                                    Building and installing zlib; this may take several minutes                                                                                                                                             ================================================================================                                                                                                                              ================================================================================                                                                                                                                    Trying to download git://https://bitbucket.org/petsc/pkg-triangle for TRIA                                                                                                                              ================================================================================                                                                                                                              ================================================================================                                                                                                                                    Compiling Triangle; this may take several minutes                                                                                                                                                       ================================================================================                                                                                                                              ^C                      Traceback (most recent call last):

**Comment by aremorov** [comment] 2023-03-03 16:05
I was mistaken, there is a configure.log, but it is in /waiwera/external/PETSc. This is what is says at the end (about triangle):

TESTING: consistencyChecks from config.packages.Triangle(config/BuildSystem/config/package.py:963)
  Checks run on the system and currently installed packages that need to be correct for the package now being configured
          =============================================================================================
TESTING: checkDependencies from config.packages.Triangle(config/BuildSystem/config/package.py:872)
          =============================================================================================
TESTING: configureLibrary from config.packages.Triangle(config/BuildSystem/config/packages/Triangle.py:127)
==================================================================================
            Checking for a functional Triangle
                    Looking for TRIANGLE at git.triangle, hg.triangle or a directory starting with ['petsc-pkg-triangle', 'Triangle']
                    Found a copy of TRIANGLE in git.triangle
Executing: ['git', 'rev-parse', '--git-dir']
stdout: .git
Executing: ['git', 'cat-file', '-e', 'v1.3-p2^{commit}']
Executing: ['git', 'rev-parse', 'v1.3-p2']
stdout: 83097fb451da7944460445a6f55008c3de0fae8b
Executing: ['git', '-c', 'user.name=petsc-configure', '-c', 'user.email=petsc@configure', 'stash']
stdout: No local changes to save
Executing: ['git', 'clean', '-f', '-d', '-x']
stdout:
Removing make.inc
Removing pkg.gitcommit
Executing: ['git', 'checkout', '-f', '83097fb451da7944460445a6f55008c3de0fae8b']
Executing: uname -s
stdout: Linux
Have to rebuild TRIANGLE, /gpfs/fs1/home/a/aswidins/aremorov/waiwera/external/PETSc/release/externalpackages/git.triangle/make.inc != /gpfs/fs1/home/a/aswidins/aremorov/waiwera/external/PETSc/release/lib/petsc/conf/pkg.conf.triangle
                        =============================================================================================
                              Compiling Triangle; this may take several minutes
                        =============================================================================================
                      
Executing: cd /gpfs/fs1/home/a/aswidins/aremorov/waiwera/external/PETSc/release/externalpackages/git.triangle && make clean && make libtriangle.a && make clean

**Comment by aremorov** [comment] 2023-03-03 16:46
It seems like its gets stuck on the first make clean, after:
cd /gpfs/fs1/home/a/aswidins/aremorov/waiwera/external/PETSc/release/externalpackages/git.triangle

**Comment by acroucher** [comment] 2023-03-06 02:10
That's very weird - never had any problems with Triangle anywhere else.

What happens if you just navigate to  that directory and do ``make clean`` manually?

**Comment by aremorov** [comment] 2023-03-08 21:36
Doing make clean manually made it get stuck forever. 

The server staff provided the solution:

1. Triangle's makefile sets SHELL=/usr/bin/bash, instead of the default
/bin/sh.
2. When 'make clean' is run, because SHELL is bash and not sh, your
.bashrc is loaded.
3. Your .bashrc attempts to load a version of conda installed on mist.
4. This executes a python script with python compiled for ppc64le, which
should fail with a "bad interpreter" error. However, bash appears to
silently ignore the error, and interprets the python script as a shell
script.
5. The first line in the python script is 'import sys', and 'import' is
a program for taking screen captures.
6. If you logged in with X11 forwarding enabled, then import will "hang"
waiting for you to select which part of the screen to capture.

They provided a script which fixes this (
[script.txt](https://github.com/waiwera/waiwera/files/10925450/script.txt)
) and the quotation issue related to the -O3 compiler), so the native installation finally worked, and parallel with mpiexec works too!

Thank you very much for all the help!

**Comment by acroucher** [comment] 2023-03-08 22:20
Wow. So I guess it all depends what is in your .bashrc file. Maybe that is why I've never seen Triangle cause any trouble before. Good detective work from your server staff!

I still don't really understand why the -O3 quoting was an issue on your system and nowhere else.

Anyway, that's great that we finally got it to work!

**Closed by acroucher** 2023-03-08 22:20 UTC
